apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: hamzakhouya10/deeplog_model:1.0.4
          ports:
            - containerPort: 8050
      imagePullSecrets:
          - name:  docker-hub
         
---
apiVersion: v1
kind: Service
metadata:
  name: model
spec:
  type: NodePort
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050