name: Deploy ML Model to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.21.3"
        id: install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./CICD/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deeplog:latest
          
       - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube cluster
        run: minikube start

      - name: Deploy DeepLog to Amazon EKS
        run:  kubectl apply -f /CICD/deploy  