name: Deploy ML Model to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.21.3"
        id: install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deeplog_model:1.0.3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Deploy to minikube
        run: kubectl apply -f deployments.yaml 
        
      - name: Test service URLs
        run: |
             minikube status
             kubectl describe deployments.apps model
             minikube service list
             minikube service model --url    
             kubectl get pod --watch 
